In [1]:
#1. What is a Python library? Why ^o we use Python libraries?
"""A Python library is a collection of related modules that contain precompiled code for some specific tasks or operations.
We use Python libraries to avoid writing the same code again and again, and to make our programming easier and more convenient.
Python libraries also provide us with various functionalities and features that are not available in the standard library, such as machine learning, data science, data visualization, web development, and more. 
Sme examples of popular Python libraries are TensorFlow, Matplotlib, Pandas, Django, and Flask"""

'A Python library is a collection of related modules that contain precompiled code for some specific tasks or operations.\nWe use Python libraries to avoid writing the same code again and again, and to make our programming easier and more convenient.\nPython libraries also provide us with various functionalities and features that are not available in the standard library, such as machine learning, data science, data visualization, web development, and more. \nSme examples of popular Python libraries are TensorFlow, Matplotlib, Pandas, Django, and Flask'

In [2]:
#2. What is the ^ifference between Numpy array an^ List?

"""A numpy array and a list are both data structures in Python, but they have some key differences. Here are some of them:

A numpy array is a homogeneous array, which means all the elements have the same data type. A list is a heterogeneous list, which means the elements can have different data types12.
A numpy array has a fixed size and shape, which means you cannot append or remove elements without making a copy. A list has a dynamic size, which means you can append or remove elements easily13.
A numpy array is optimized for numerical computations and supports vectorized operations, which makes them faster and more efficient than lists. A list is a general-purpose data structure that can hold any kind of object, but is not optimized for numerical operations12.
A numpy array is stored in contiguous memory locations, which reduces memory overhead and improves performance. A list is stored as a sequence of references to objects, which increases memory overhead and may cause memory fragmentation"""

'A numpy array and a list are both data structures in Python, but they have some key differences. Here are some of them:\n\nA numpy array is a homogeneous array, which means all the elements have the same data type. A list is a heterogeneous list, which means the elements can have different data types12.\nA numpy array has a fixed size and shape, which means you cannot append or remove elements without making a copy. A list has a dynamic size, which means you can append or remove elements easily13.\nA numpy array is optimized for numerical computations and supports vectorized operations, which makes them faster and more efficient than lists. A list is a general-purpose data structure that can hold any kind of object, but is not optimized for numerical operations12.\nA numpy array is stored in contiguous memory locations, which reduces memory overhead and improves performance. A list is stored as a sequence of references to objects, which increases memory overhead and may cause memory f

In [3]:
#3. Fin^ the shape, size an^ ^imension of the following array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

import numpy as np
array = np.array ( [ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Shape of the array:", array.shape)
print("Size of the array:", array.size)
print("Dimension of the array:", array.ndim)




Shape of the array: (3, 4)
Size of the array: 12
Dimension of the array: 2


In [4]:
#4. Write python co^e to access the first row of the following array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]


# Define the array as a list of lists
array = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

# Access the first row by using index 0
first_row = array[0]

# Print the first row
print(first_row)


[1, 2, 3, 4]


In [5]:
#5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]


# Create the numpy array
a = np.array ( [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Indexing starts from zero, so the third row is at index 2
# and the fourth column is at index 3
# Use square brackets to access the element
element = a [2, 3]

# Print the element
print (element)


12


In [6]:
#6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

import numpy as np

# Define the numpy array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Use slicing to get the odd-indexed elements
odd_arr = arr[:, 1::2]

# Print the result
print(odd_arr)



[[ 2  4]
 [ 6  8]
 [10 12]]


In [7]:
#7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?
# Import numpy library
import numpy as np

# Create a 3x3 array with random values from [0, 1)
random_matrix = np.random.rand(3, 3)

# Print the array
print(random_matrix)




[[0.78648626 0.54888384 0.14990989]
 [0.35769572 0.82492714 0.84681042]
 [0.44405736 0.69241806 0.34658529]]


In [8]:
#8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?
"""The main difference between np.random.rand and np.random.randn is the probability distribution from which they generate random numbersnp.random.rand produces numbers from a uniform distribution over the interval [0, 1), while np.random.randn produces numbers from a normal (Gaussian) distribution with a mean of 0 and a standard deviation of 112.
This means that the numbers generated by np.random.rand are equally likely to fall anywhere in the range [0, 1), while the numbers generated by np.random.randn are more likely to be close to 0 and less likely to be very large or very small. The shapes of these distributions are shown below:
Uniform distribution:f(x)={10​if 0≤x<1otherwise​
Normal distribution:f(x)=2π​1​e−2x2​
The choice of which function to use depends on the purpose and the context of the random numbers. For example, if you want to simulate a fair coin toss, you can use np.random.rand and assign heads or tails based on whether the number is greater or less than 0.5. If you want to model the heights of people in a population, you can use np.random.randn and scale the numbers by the average height and the standard deviation. In general, np.random.randn is more suitable for situations where the random numbers have a natural center and a spread around it, while np.random.rand is more suitable for situations where the random numbers are uniformly distributed over a fixed interval."""


'The main difference between np.random.rand and np.random.randn is the probability distribution from which they generate random numbersnp.random.rand produces numbers from a uniform distribution over the interval [0, 1), while np.random.randn produces numbers from a normal (Gaussian) distribution with a mean of 0 and a standard deviation of 112.\nThis means that the numbers generated by np.random.rand are equally likely to fall anywhere in the range [0, 1), while the numbers generated by np.random.randn are more likely to be close to 0 and less likely to be very large or very small. The shapes of these distributions are shown below:\nUniform\xa0distribution:f(x)={10\u200bif\xa00≤x<1otherwise\u200b\nNormal\xa0distribution:f(x)=2π\u200b1\u200be−2x2\u200b\nThe choice of which function to use depends on the purpose and the context of the random numbers. For example, if you want to simulate a fair coin toss, you can use np.random.rand and assign heads or tails based on whether the number is

In [9]:
#9. Write co^e to increase the ^imension of the following array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

import numpy as np
# create a 2D array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
# print the shape of the array
print(arr.shape) # (3, 4)
# increase the dimension by adding a new axis
arr = np.expand_dims(arr, axis=0)
# print the shape of the new array
print(arr.shape) # (1, 3, 4)



(3, 4)
(1, 3, 4)


In [10]:
#10. How to transpose the following array in NumPy?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]


import numpy as np
# create a 2D array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
# print the shape and the array
print(arr.shape) # (3, 4)
print(arr)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

# transpose the array using the transpose method
arr_t = arr.transpose()
# print the shape and the transposed array
print(arr_t.shape) # (4, 3)
print(arr_t)
# [[ 1  5  9]
#  [ 2  6 10]
#  [ 3  7 11]
#  [ 4  8 12]]

# transpose the array using the .T attribute
arr_t = arr.T
# print the shape and the transposed array
print(arr_t.shape) # (4, 3)
print(arr_t)
# [[ 1  5  9]
#  [ 2  6 10]
#  [ 3  7 11]
#  [ 4  8 12]]


(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(4, 3)
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
(4, 3)
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [11]:
#11. Consi^er the following matrix:
#Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
#Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [13]:
# index wise multipication

import numpy as np
# create two matrices A2 and B2
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
# perform index-wise multiplication
C2 = np.multiply(A2, B2)
# or equivalently
C2 = A2 * B2
# print the result
print(C2)



[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [23]:
#matrix multipacti


In [22]:
#import numpy as np
# create two matrices A2 and B2
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
# perform matrix multiplication
C2 = np.matmul(A2, B2)
# or equivalently
C2 = A2 @ B2
# print the result
print(C2)


In [1]:
#add both the matrix

import numpy as np
# create two matrices A2 and B2
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
# add the matrices using np.add
C2 = np.add(A2, B2)
# or equivalently using +
C2 = A2 + B2
# print the result
print(C2)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [2]:
# subtract b from a

import numpy as np
# create two matrices A2 and B2
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
# add the matrices using np.add
C2 = np.add(A2, B2)
# or equivalently using +
C2 = A2 + B2
# print the result
print(C2)



[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [3]:
# devided matrix b by a

import numpy as np
# create two matrices A2 and B2
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
# divide B2 by A2 using np.divide
C2 = np.divide(B2, A2)
# or equivalently using /
C2 = B2 / A2
# print the result
print(C2)



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
#12. Which function in Numpy can be use^ to swap the byte or^er of an array?
"""One function in NumPy that can be used to swap the byte order of an array is np.ndarray.byteswap. This function toggles between low-endian and big-endian data representation by returning a byteswapped array, optionally swapped in-place"""

import numpy as np
# create an array of 16-bit integers
arr = np.array( [1, 256, 8755], dtype=np.int16)
# print the array in hexadecimal
print(list(map(hex, arr))) # ['0x1', '0x100', '0x2233']
# swap the bytes of the array
arr.byteswap(inplace=True)
# print the swapped array in hexadecimal
print(list(map(hex, arr))) # ['0x100', '0x1', '0x3322']





['0x1', '0x100', '0x2233']
['0x100', '0x1', '0x3322']


In [5]:
"""Another function in NumPy that can be used to change the byte order of an array is np.ndarray.newbyteorder. This function changes the byte-ordering information in the array dtype so that it interprets the underlying data as being in a different byte orde"""

import numpy as np
# create an array of 32-bit integers
arr = np.array( [1, 2, 3], dtype=np.int32)
# print the array in hexadecimal
print(list(map(hex, arr))) # ['0x1', '0x2', '0x3']
# change the byte order of the array to big-endian
arr = arr.newbyteorder('>')
# print the array in hexadecimal
print(list(map(hex, arr))) # ['0x1000000', '0x2000000', '0x3000000']



['0x1', '0x2', '0x3']
['0x1000000', '0x2000000', '0x3000000']


In [6]:
#13. What is the significance of the np.linalg.inv function?


"""The np.linalg.inv function is a NumPy function that computes the (multiplicative) inverse of a square matrix. The inverse of a matrix is such that if it is multiplied by the original matrix, it results in an identity matrix. The inverse of a matrix can be used to solve systems of linear equations, find the determinant of a matrix, or perform other matrix operations"""

'The np.linalg.inv function is a NumPy function that computes the (multiplicative) inverse of a square matrix. The inverse of a matrix is such that if it is multiplied by the original matrix, it results in an identity matrix. The inverse of a matrix can be used to solve systems of linear equations, find the determinant of a matrix, or perform other matrix operations'

In [7]:
#14. What ^oes the np.reshape function ^o, an^ how is it use^?

"""The np.reshape function is a NumPy function that changes the shape of an array without changing its data. It takes an array and a new shape as arguments, and returns a new array with the same data but with the new shape. The new shape must be compatible with the original shape, meaning that the total number of elements must be the same. One of the dimensions can be -1, which means that the value is inferred from the other"""


import numpy as np
# create a 2D array of shape (3, 4)
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
# reshape the array into a 1D array of shape (12,)
arr = np.reshape(arr, -1)
# or equivalently
arr = np.reshape(arr, 12)
# print the reshaped array
print(arr) # [ 1  2  3  4  5  6  7  8  9 10 11 12]
# reshape the array into a 3D array of shape (2, 2, 3)
arr = np.reshape(arr, (2, 2, 3))
# print the reshaped array
print(arr)
# [[[ 1  2  3]
#   [ 4  5  6]]
#  [[ 7  8  9]
#   [10 11 12]]]



[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
#15. What is broa^casting in Numpy?

"""
Broadcasting in NumPy is a way of performing arithmetic operations on arrays with different shapes. It allows the smaller array to be “stretched” or “broadcasted” across the larger array so that they have compatible shapes. Broadcasting enables vectorization of array operations, which means that the looping is done in C instead of Python, resulting in faster and more efficient computations"""



import numpy as np
# create a 2D array of shape (3, 4)
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
# create a 1D array of shape (4,)
b = np.array([10, 20, 30, 40])
# add the 1D array to each row of the 2D array using broadcasting
c = a + b
# print the result
print(c)



[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


In [9]:
## COMPLETE##